pepfile: config/pep/config.yaml

# for testing, uncomment to limit to n strain genomes
limit-strain-genomes: 5
benchmark-genomes:
  - MT971460
  - MT810976
  - MW184368
  - MT470120
  - MT451810


data-handling:
  # path of incoming data
  incoming: ../incoming/
  # path to store data in the workflow
  data: data/
  # path to archive data from incoming to
  archive: ../archive/


RKI-quality-criteria:
  illumina:
    # minimal length of acceptable reads
    min-length-reads: 30
    # average quality of acceptable reads (PHRED)
    min-PHRED: 20
  ont:
    # minimal length of acceptable reads
    min-length-reads: 200
    # average quality of acceptable reads (PHRED)
    min-PHRED: 10
  # identity to NC_045512.22 of reconstructed genome
  min-identity: 0.9
  # share N in the reconstructed genome
  max-n: 0.05
  # minimum local sequencing depth without filtering of PCR duplicates
  min-depth-with-PCR-duplicates: 20
  # minimum local sequencing depth after filtering PCR duplicates
  min-depth-without-PCR-duplicates: 10
  # minimum informative allele frequency
  min-allele: 0.9
  # frameshift-Mutationen


variant-calling:
  # false discovery rate to control for
  fdr: 0.05
  # downsample loci to this read depth
  max-read-depth: 2000
  report:
    # downsample loci to this read depth for visualization in report
    max-read-depth: 100
  filters:
    low-impact: 'ANN["IMPACT"] in ["LOW", "MODIFIER"]'
    high+moderate-impact: 'ANN["IMPACT"] in ["HIGH", "MODERATE"]'


strain-calling:
  # minimum reported strain fraction after quantification
  min-fraction: 0.02
  # flag for using gisaid or genbank 
  use-gisaid: False
  # path to meta data from GISAID
  gisaid-metadata: resources/gisaid/metadata_2021-02-09_18-08.tsv
  # path to sequences fasta from GISAID
  gisaid-metafasta: resources/gisaid/sequences_2021-02-09_08-13.fasta
  # paths to store genomes that are extracted from the full GISAID data
  extracted-strain-genomes: resources/genomes


adapters:
  #  Illumina TruSeq adapters
  illumina-revelo: "--adapter_sequence AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  illumina-nimagen: "--adapter_sequence GCGAATTTCGACGATCGTTGCATTAACTCGCGAA --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  amplicon-primers: "resources/primer.bedpe"
  amplicon-reference: "MN908947"

rki-output:
# minimum contig length
  minimum-length: 20000


# NCBI reference sequences of non-SARS-CoV-2 coronavirus. 
# Used to test whether the pipeline can distinguish between 
# non-SARS CoV-2 and SARS CoV-2 viruses.
non_cov2_genomes:
  - NC_005831
  - NC_002645
  - NC_006213
  - NC_006577
  - NC_019843
  # - NC_004718

# For testing the read bases strain calling
mixtures:
  # maximal number of reads to generate
  max_reads: 584903
  # number of mixtures to generate
  no_mixtures: 500
  # number of strains to mix
  no_strains: 2
  # or you can specify the mix you would like to have 
  # this assumes, that strain files are available under resources/genomes
  # the used number of strains must match the no_strains defined above
  use_predefined_mixtures: True
  # use the following format: "%B-1-1-7=90%B-1-351=10"
  predefined_mixtures:
    - "?B-1-1-7!50?B-1-351!50"
    - "?B-1-1-7!90?B-1-351!10"

# variants of concern
voc:
  - N501Y
  - E484K